/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#afcbd8",
        "secondary-container": "#cbe7f5",
        "on-primary-fixed": "#001b3d",
        "outline-variant": "#c2c6d4",
        "surface-tint": "#005db5",
        "primary-container": "#005fb8",
        "inverse-on-surface": "#eff1f3",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-primary-container": "#cadcff",
        "primary-fixed-dim": "#a8c8ff",
        "on-tertiary-fixed-variant": "#783100",
        "primary-fixed": "#d6e3ff",
        "tertiary-fixed": "#ffdbcb",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#341100",
        "tertiary-container": "#a04401",
        "secondary-fixed": "#cbe7f5",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e5",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#304a55",
        "on-surface-variant": "#424752",
        "on-error-container": "#93000a",
        "primary": "#00488d",
        "surface": "#f7f9fb",
        "background": "#f7f9fb",
        "on-secondary-fixed": "#021f29",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef0",
      },
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}